apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs-static
  namespace: roboshop
spec:
  capacity:
    storage: 5Gi  
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain # retain means 
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0d0026161fc879288
    fsType: ext4

  