
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: roboshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-efs-dynamic
  namespace: roboshop
labels:
  purpose: efs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: efs-volume
      mountPath: /usr/share/nginx/html # this is the path where the pv will be mounted in the container

  volumes:
  - name: efs-volume
    persistentVolumeClaim:
      claimName: efs-pvc # this is the name of the pvc that we want to use
  



  
