
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs-static
  namespace: roboshop
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f0288bd1a703ba2c
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-efs-static
  namespace: roboshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-efs-static

---
apiVersion: v1
kind: Pod
metadata:
name: nginx-efs-static
namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: efs-volume
      mountPath: /usr/share/nginx/html # this is the path where the pv will be mounted in the container
    
  
  volumes:
  - name: efs-volume
    persistentVolumeClaim:
      claimName: pvc-efs-static # this is the name of the pvc that we want to use