apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: roboshop
  labels:
    purpose: nginx-headless
    project: roboshop
spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: nginx-headless
      project: roboshop
  template:             # this is the pod template
    metadata:
      labels:
        purpose: nginx-headless
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:latest
     

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    purpose: nginx-headless
    project: roboshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

