apiVersion: v1

kind: Pod
metadata:
  name: multi-container
  namespace: roboshop
  labels:
    project: roboshop
spec:
  containers: 
  - name: nginx
    image: nginx:latest
    
   
  - name: almalinux
    image: almalinux:latest
    commands: ["sleep", "1000"]
    
 
