apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  namespace: roboshop
  #labels help to register the pod with service
  labels:
    name: frontend
    environment: dev
    purpose: node-frontend
spec:
  containers: 
  - name: nginx
    image: nginx:latest
    